add insmod all_video
mdamt/haftian pull request #2
Opened 2017-06-16 09:17 UTC by princeofgiri

it can fix stuck process in few computer with hybrid graphic card

2017-06-17 04:11 UTC, mdamt requested changes

2017-06-17 04:11 UTC, mdamt commented on haftian
> +sed -i 's/set default=0 # Set the default menu entry/set default=0 # Set the default menu entry\ninsmod all_video/' boot/grub/grub.cfg
`echo "insmod all_video" >> boot/grub/grub.cfg` is better

2017-06-19 01:55 UTC, princeofgiri commented
use suggestion from previous comment

2017-06-19 01:59 UTC, mdamt approved these changes

2017-06-19 01:59 UTC, merged